// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Only web is defined here for the chrome preview.
    // Run `flutterfire configure` to generate the full file for all platforms.
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_API_KEY',
    appId: 'REPLACE_WITH_ACTUAL_APP_ID',
    messagingSenderId: 'REPLACE_WITH_ACTUAL_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_ACTUAL_PROJECT_ID',
    authDomain: 'REPLACE_WITH_ACTUAL_AUTH_DOMAIN',
    storageBucket: 'REPLACE_WITH_ACTUAL_STORAGE_BUCKET',
  );
}
